import re

# install buck
#
# npm start
#
# cd android
#
# keytool
#
# gradlew, make all gradle dep to buck
#
# buck install
#
# To learn about Buck see [Docs](https://buckbuild.com/).
# To run your application with Buck:
# - install Buck
# - `npm start` - to start the packager
# - `cd android`
# - `keytool -genkey -v -keystore keystores/debug.keystore -storepass android -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US"`
# - `./gradlew :app:copyDownloadableDepsToLibs` - make all Gradle compile dependencies available to Buck
# - `buck install -r android/app` - compile, install and run application
#

# lib deps
lib_deps = []

# for jar file in libs/*.jar
for jarfile in glob(['libs/*.jar']):
  # jars__/xxxx/xxx.jar
  name = 'jars__' + re.sub(r'^.*/([^/]+)\.jar$', r'\1', jarfile)
  
  # lib deps, append name
  lib_deps.append(':' + name)
  prebuilt_jar(
    name = name,
    binary_jar = jarfile,
  )

# .arr file amber graphic file
for aarfile in glob(['libs/*.aar']):
  name = 'aars__' + re.sub(r'^.*/([^/]+)\.aar$', r'\1', aarfile)
  lib_deps.append(':' + name)
  android_prebuilt_aar(
    name = name,
    aar = aarfile,
  )

# android lib
# all lib
android_library(
  name = 'all-libs',
  exported_deps = lib_deps
)

# app-code
# src/main/java/.../.../*.java
android_library(
  name = 'app-code',
  srcs = glob([
    'src/main/java/**/*.java',
  ]),
  deps = [
    ':all-libs',
    ':build_config',
    ':res',
  ],
)

# com.hagnosticnews
# config
android_build_config(
  name = 'build_config',
  package = 'com.hagnosticnews',
)


# android resource
android_resource(
  name = 'res',
  res = 'src/main/res',
  package = 'com.hagnosticnews',
)


# android, binary
# src/main/manifest.xml
# key store
android_binary(
  name = 'app',
  package_type = 'debug',
  manifest = 'src/main/AndroidManifest.xml',
  keystore = '//android/keystores:debug',
  deps = [
    ':app-code',
  ],
)
